### PR TITLE
Fix bracket thing

### PR DESCRIPTION
**Pull request by fw42**
Fixes https://github.com/Shopify/liquid/issues/625.

@trishume @pushrax

### CODE REVIEW

**Comment by trishume** [comment]
Cool, as far as I can tell this is the correct fix that matches what we would expect the grammar to be. It is only this way because the liquid grammar is simple, this wouldn't be the correct way to handle things if liquid had other postfixes on identifiers like function call brackets.

:+1:

**Comment by pushrax** [comment]
:+1:

**Comment by fw42** [comment]
Backported to 3-0-stable in https://github.com/Shopify/liquid/commit/8f84ddb5ce8b3296b781ee269d1f1d9ce0ea3750 and pushed 3.0.4 to Rubygems.

@parkr you might want to bump Liquid in Jekyll 3.

**Comment by parkr** [comment]
> @parkr you might want to bump Liquid in Jekyll 3.

`~> 3.0, >= 3.0.4`? Is 3.0.0-3.0.3 unusable?

**Comment by fw42** [comment]
ah ok ~> 3.0 should do. I thought you were locked 3.0.3 or something.

**Pull request merged**
