### PR TITLE
Fixed for Ruby 1.9.3

### PR DESCRIPTION
**Pull request by ryanfox1985**
Hi the code fails in Ruby 1.9.3, I did a refactor :)

### CODE REVIEW

**Comment by fw42** [comment]
Ruby 1.9.3 support will be dropped in the next major release of Liquid.

**Comment by parkr** [comment]
I thought 3.x did that?

**Comment by fw42** [comment]
Liquid 3.x dropped support for Ruby 1.8.x. Liquid 4.x will drop support for Ruby 1.9.x.

**Comment by ryanfox1985** [comment]
Well, I don't understand why do you drop the support to 1.9.3.
Regards!

**Comment by fw42** [comment]
Because Ruby 1.9 has been deprecated by the Ruby core team in February 2015 and we would like to be able to use features of Ruby that are exclusive to Ruby 2.x in the future (like keyword arguments for example).

**Pull request closed without merging**
