### PR TITLE
Liquid 3.0.2

### PR DESCRIPTION
**Pull request by fw42**
This cherry-picks https://github.com/Shopify/liquid/pull/551 into 3-0-stable.

Closes https://github.com/Shopify/liquid/issues/547.

@arthurnn @pushrax, are we cool with this? If so, I will push 3.0.2 to Rubygems.

FYI @willlahr

### CODE REVIEW

**Comment by fw42** [comment]
Also include https://github.com/Shopify/liquid/pull/489. Closes https://github.com/Shopify/liquid/issues/552.

**Comment by pushrax** [comment]
How about including #551 as well?

**Comment by pushrax** [comment]
Also #550 to get the tests passing.

**Comment by fw42** [comment]
Added a1b209d212b4c7abaeeb91bcf707bb4f7774bb46 (#550)

**Comment by fw42** [comment]
@arthurnn :+1:?

**Comment by arthurnn** [comment]
changelog?

**Comment by pushrax** [comment]
I'll move the related entries for 4 into this branch in the 3.0.2 section.

**Comment by pushrax** [comment]
@arthurnn if that looks ok I'll sync History.md in master.

**Comment by arthurnn** [comment]
Cool.. thanks.
We need to keep in mind to always update the history, when we backport things too.

**Comment by fw42** [comment]
@pushrax: Can we merge this now?

**Comment by pushrax** [comment]
Release away!

**Comment by parkr** [comment]
:confetti_ball:

**Pull request merged**
