### PR TITLE
Fix post-trim for the raw tag

### PR DESCRIPTION
**Pull request by XrXr**
The added test did not pass before this commit.

### CODE REVIEW

**Comment by XrXr** [comment]
I also have a more general solution that tries to solve this for anything that implements a custom `parse`. I almost have it working, but it didn't seem worth it to pursue more as it introduces a lot of code.

**Comment by shopmike** [comment]
Whitespace control was the first time I had touched the Liquid repo and now in hindsight, I feel like it should have been part of the tokenizer. By changing the tokenizer it wouldn't need to look backwards and forwards as it does right now.

**We currently have this**
```
  TemplateParser              = /(#{PartialTemplateParser}|#{AnyStartingTag})/om
```

By having it also consume whitespace around it would keep all the whitespace attached to the token that controls whether it is displayed or not.

```
  TemplateParser              = /(/s*#{PartialTemplateParser}|#{AnyStartingTag}/s*)/om
```

@pushrax thoughts?

**Comment by shopmike** [comment]
This change would also impact the `format` command which is why I'm suggesting a bigger change. I've pretty much had to store a `left` and `right` of whitespace on tokens anyway for it to be able to rebuild a template from the AST.

**Comment by XrXr** [comment]
Closing as this has rotted and doesn't seem to be going anywhere.

**Pull request closed without merging**
