### PR TITLE
Use `Regexp#match?` when `MatchData` is not used

### PR DESCRIPTION
**Pull request by ashmaroli**
*As reported and corrected by RuboCop*

Closes #991

### CODE REVIEW

**Comment by shopmike** [comment]
So looks like this Performance cop doesn't run because the target version isn't set. Do you want to commit the following along with this as it means this pull request bumps Rubocop to performance gains for `2.4`

```
AllCops:
  TargetRubyVersion: 2.4
```
I thought Rubocop would just work out the ruby version from the `gemspec` but clearly not

**Comment by ashmaroli** [comment]
TBH, I did add that change to the config file but left it out of the commit.. :stuck_out_tongue:

**Comment by ashmaroli** [comment]
@shopmike in case you didn't know, #991 would've been automatically closed by GitHub (with the associated references) when this PR gets merged.

**Comment by shopmike** [comment]
Haha yeah,  I just noticed that when I closed it, it said it was going to be closed by this PR anyway. I need to learn all these GH tricks.

**Pull request merged**
