### PR TITLE
Use VariableSignature as Syntax for Capture tag to allow hyphens in variable names

### PR DESCRIPTION
**Pull request by fw42**
Fixes https://github.com/Shopify/liquid/issues/505

@arthurnn @dylanahsmith @davidrleonard

### CODE REVIEW

**Comment by fw42** [comment]
@pushrax @xthexder FYI not sure how relevant this is to Liquid C.

**Comment by parkr** [comment]
:+1:

**Comment by pushrax** [comment]
:+1: liquid-c won't be impacted by this.

**Comment by arthurnn** [comment]
:+1:

**Comment by parkr** [comment]
A chorus of thumbs sings your praises, @fw42.

**Pull request merged**
