### PR TITLE
Prefer Class.new() where possible

### PR DESCRIPTION
**Pull request by fw42**
If [Eric Wong](https://github.com/defunkt/unicorn/commit/d8109e5e531ceca5a4d1c0a4f9e4d625f74e336b) does it, it must be good!

@byroot

### CODE REVIEW

**Comment by byroot** [comment]
Lol that's foolproof argument I guess.

Code LGTM and I prefer that style anyway. But I would love to hear the explanation behind the 200bytes saving.

**Comment by Sirupsen** [comment]
:fr: @byroot

**Comment by camilo** [comment]
meh LGTM as it was before, if the savings are real :+1:  if not meh

**Comment by pushrax** [comment]
the savings don't matter at all really.. but :+1: for style

**Comment by camilo** [comment]
why is this better style? IMO is just diff

**Comment by byroot** [comment]
Because `; end` is super ugly.

**Comment by camilo** [comment]
I think is pretty... lol

**Comment by parkr** [comment]
:clap:

**Pull request merged**
