### PR TITLE
Allow variables to start with contains in strict parser

### PR DESCRIPTION
**Pull request by evulse**
Links with Issue #788

### CODE REVIEW

**Comment by parkr** [comment]
LGTM.

**Comment by veleek** [comment]
Ping, when is this going to be merged?  I'm running into this issue.

**Comment by fw42** [comment]
LGTM too. @dylanahsmith?

**Comment by fw42** [comment]
Can you add a note to the History file? Will merge it after that

**Comment by evulse** [comment]
@fw42 History updated

**Comment by fw42** [comment]
This should now be in production. Thanks for your contribution!

**Pull request merged**
