### PR TITLE
Handle nils gracefully when using the "sort" filter

### PR DESCRIPTION
**Pull request by carsonreinke**
Since there is no reject filter, allow sorting when a value could be nil.

### CODE REVIEW

**Comment by carsonreinke** [comment]
I guess I mean compact, not reject.

**Comment by fw42** [comment]
FWIW I would be okay with adding a `compact` filter

**Comment by fw42** [comment]
Hmm. Not super sure how I feel about this. Can you explain your use-case?

**Comment by pushrax** [comment]
:+1: to adding a compact filter instead of this. As someone who prefers static type systems this feels wrong to me.

**Comment by carsonreinke** [comment]
Yep, it looked weird.

**Pull request closed without merging**
