### PR TITLE
Adding tests verifying documentation

### PR DESCRIPTION
**Pull request by sebastienros**
Validation if documentation that states that `'Tobi' == true` is true is correct.
https://shopify.dev/docs/themes/liquid/reference/basics/true-and-false

### CODE REVIEW

**Comment by sebastienros** [comment]
CLA signed. Check needs to be re-run.

From the test results, assuming it ran then, the documentation is wrong.

**Review by daviburg — APPROVED** [review]

**Comment by sebastienros** [comment]
I have already signed the CLA but the bot keeps requiring it. I tried to sign again but then got a validation error that it was already signed.

**Comment by daviburg** [comment]
> I have already signed the CLA but the bot keeps requiring it. I tried to sign again but then got a validation error that it was already signed.

Did you sign the individual contribution CLA? Does it want a corporate CLA signed? I don't know of the status of Microsoft with Shopify agreement if any.

**Comment by daviburg** [comment]
Who can we tag from Shopify to help here?

**Comment by daviburg** [comment]
@peterzhu2118 could you help confirm if the Shopify documentation example for truthy is wrong or if the implementation is wrong? The two contradict each other.

**Comment by peterzhu2118** [comment]
Thank you for letting us know. I will investigate this and will update you soon.

**Comment by peterzhu2118** [comment]
The shopify.dev page should now be updated with the correct example so I will be closing this PR. Thank you for bringing this to our attention.

**Pull request closed without merging**
