### PR TITLE
Modernize code base with __dir__ and require_relative

### PR DESCRIPTION
**Pull request by byroot**
@fw42 as proposed here: https://github.com/Shopify/liquid/pull/564#discussion_r30266546

### CODE REVIEW

**Comment by fw42** [comment]
tests are failing

**Comment by byroot** [comment]
On circle only because circle use 1.9 by default.

**Comment by byroot** [comment]
I added a circle.yml and that fixed it. Not sure if it's a problem to have one.

**Comment by fw42** [comment]
:+1: when :green_apple:

**Pull request merged**
