### PR TITLE
WIP: Spike out the documentation

### PR DESCRIPTION
**Pull request by parkr**
/cc #513

@Tetsuro @fw42 

- [ ] Filters
  - [x] append
  - [x] capitalize
  - [x] ceil
  - [x] date
  - [x] default
  - [x] divided_by
  - [x] downcase
  - [x] escape
  - [x] escape_once
  - [x] first
  - [x] floor
  - [ ] h
  - [x] join
  - [x] last
  - [x] lstrip
  - [x] map
  - [x] minus
  - [x] modulo
  - [x] newline_to_br
  - [x] plus
  - [x] prepend
  - [x] remove
  - [x] remove_first
  - [x] replace
  - [x] replace_first
  - [ ] reverse
  - [ ] round
  - [x] rstrip
  - [ ] size
  - [ ] slice
  - [ ] sort
  - [ ] split
  - [x] strip
  - [ ] strip_html
  - [ ] strip_newlines
  - [ ] times
  - [ ] truncate
  - [ ] truncatewords
  - [ ] uniq
  - [ ] upcase
  - [ ] url_encode
- [ ] Tags
  - [ ] `{% break %}`
  - [ ] `{% assign %}`
  - [ ] `{% case %}`
  - [ ] `{% continue %}`
  - [ ] `{% comment %}`
  - [ ] `{% cycle %}`
  - [ ] `{% decrement %}`
  - [ ] `{% ifchanged %}`
  - [ ] `{% include %}`
  - [ ] `{% increment %}`
  - [ ] `{% tablerow %}`
- [ ] Blocks
  - [ ] `{% capture %}`
  - [ ] `{% for %}`
  - [ ] `{% if %}`
  - [ ] `{% raw %}`
  - [ ] `{% unless %}`

### CODE REVIEW

**Comment by parkr** [comment]
Just going through this ATM: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb

**Comment by parkr** [comment]
Shout-out to @gjtorikian who is the dopes for contributing docs here as well!! :tada:

**Comment by gjtorikian** [comment]
@parkr I can't actually update the task list because I don't have collab writes to this repo. But, the list is a bit out of date. :wink:

**Comment by parkr** [comment]
> @parkr I can't actually update the task list because I don't have collab writes to this repo. But, the list is a bit out of date.

YOU ARE THE COOLEST HUMAN EVER

**Comment by Tetsuro** [comment]
Nice work guys!

I'm going to be working more on the styling of the site in the coming weeks.

**Comment by parkr** [comment]
> I'm going to be working more on the styling of the site in the coming weeks.

Sahweeeeeet. Thinking we should merge and move forward with other PR's. If others see the new docs, they can submit PR's and contribute missing docs.

**Comment by arthurnn** [comment]
:+1: to merge this.
Before I do it, where this should live? in a branch under liquid repo? or should we create a new liquid-docs repo?
thoughts @parkr @Tetsuro ?

**Comment by parkr** [comment]
@arthurnn We version jekyllrb.com in `jekyll/jekyll#master` and it seems to work pretty well for us. We can get PR's (and try to enforce this) that when you make a change to the code, you document the change (unless it doesn't change functionality). Then we deploy that code to `gh-pages` when we want to push the site out.

Not sure if that would work well for you all. Maybe version the docs under folders?

**Comment by fw42** [comment]
:-1: to new repo, it should be here on the `gh-pages` branch (eventually)

**Comment by parkr** [comment]
Added an edit link so the path to contributions is short and easy to find:

screen shot 2015-03-27 at 1 01 39 pm

**Comment by parkr** [comment]
@fw42 @Tetsuro @arthurnn Should be good to go. To test locally, check out my branch and run `jekyll serve`. Navigate to http://localhost:4000 and behold. ;)

**Comment by Tetsuro** [comment]
LGTM :+1:

**Comment by mikebridge** [comment]
While you're at it, it'd be nice to add "break" and "continue" to the documentation.  https://github.com/Shopify/liquid/issues/119

**Comment by parkr** [comment]
> While you're at it, it'd be nice to add "break" and "continue" to the documentation. #119

@mikebridge Submit a PR to the `docs-update` branch!

**Pull request merged**
