### PR TITLE
Update module_ex.rb code documentation and code style

### PR DESCRIPTION
**Pull request by Dorian**
Didn't look good on rubydoc.info: http://i.imgur.com/469N92P.png

### CODE REVIEW

**Comment by fw42** [comment]
Thanks!

**Comment by pushrax** [comment]
I'm confused about why this file says "Copyright 2007 by Domizio Demichelis."

**Comment by fw42** [comment]
dunnolol

**Comment by pushrax** [comment]
From SVN:

```
r7 | tobias.luetke | 2007-09-13 17:45:09 -0400 (Thu, 13 Sep 2007) | 2 lines

Made it a lot easier to use regular objects as liquid drops thanks to work by Domizio
```

Dunno why it needs to be copyrighted to him though, it kinda messes up the docs.

**Comment by Dorian** [comment]
Awesome, and yes, I found this Copyright comment very weird too indeed.

**Pull request merged**
