### PR TITLE
Add support for whitespace control character allowing for ERB like trim

### PR DESCRIPTION
**Pull request by evulse**
Rebase of #743. To solve issues #215 and #216

### CODE REVIEW

**Comment by evulse** [comment]
Current performance from this feature
```
Warming up --------------------------------------
              parse:     2.000  i/100ms
        parse & run:     1.000  i/100ms
Calculating -------------------------------------
              parse:     27.043  (± 3.7%) i/s -      1.622k in  60.017511s
        parse & run:     17.996  (± 5.6%) i/s -      1.079k in  60.023723s
```
Master branch
```
Warming up --------------------------------------
              parse:     2.000  i/100ms
        parse & run:     1.000  i/100ms
Calculating -------------------------------------
              parse:     27.915  (± 3.6%) i/s -      1.674k in  60.023530s
        parse & run:     18.461  (± 5.4%) i/s -      1.107k in  60.020358s
```

**Comment by evulse** [comment]
@dylanahsmith @fw42 What is the best way to have an open pull request on the liquid-c repo that this can use to fully build and pass tests?

**Comment by evulse** [comment]
This adds support for {{- and {%- syntax which will lstrip! and -}} and -%} which will rstrip!

**Comment by evulse** [comment]
Depends on Shopify/liquid-c#30 to pass all tests.

**Comment by fw42** [comment]
@Shopify/liquid, need some eyes on this (and https://github.com/Shopify/liquid-c/pull/30)

**Comment by fw42** [comment]
would you mind rebasing and squashing your commits?

**Pull request closed without merging**
